### ISSUE TITLE
Error Traceback 

### ISSUE THREAD

**Issue by wdikiz** [Ra-Na/GTranslate-strings-xml#17]
Hello, 
Every time i try to translate the a string file i got this error
could you fix it please
```

[Upload successful, processing ... 
Download link appears at the bottom after finishing.
Translation script output: 

Traceback (most recent call last):
  File "gtranslate.py", line 274, in <module>
    tree = ET.parse(INFILE)
  File "/usr/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.7/xml/etree/ElementTree.py", line 598, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 176, column 85
Exit status : 1
Translation download as XML](url)

```

**Comment by Ra-Na** [comment]
Please disclose the offending strings.xml file.

**Comment by wdikiz** [comment]
> Please disclose the offending strings.xml file.

Thank you it's resolved it the causes was this 2 SYMBOLES 

`` &   
and
&amp; 
``
Finally deleting this symbol `&`  from my phrases solve the problem.

Thank you
