### ISSUE TITLE
Could not download the XML file when i click on "Translation download as XML" button.

### ISSUE THREAD

**Issue by FidaMOhsin** [Ra-Na/GTranslate-strings-xml#43]
I'm unable to download then xml file.
I tried other search engines but could not success.
![image](https://user-images.githubusercontent.com/72807782/179668985-1893a646-dab4-413e-ab52-1a32dbfec8d0.png)

**Comment by Priyank248** [comment]
I got same error

Traceback (most recent call last):
  File "gtranslate.py", line 282, in <module>
    tree = ET.parse(INFILE)
  File "/usr/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.7/xml/etree/ElementTree.py", line 598, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 168, column 62
Exit status : 1
